apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-nodejs
  template:
    metadata:
      labels:
        app: demo-devops-nodejs
    spec:
      containers:
        - name: demo-devops-nodejs
          image: demo-devops-nodejs:latest
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: production
